### ISSUE TITLE
Heya so, idk if you care about suggestions but I got one ig.

### ISSUE THREAD

**Issue by ThatOneRetro** [MarcusKubis9/Drgregs-Dumb-Styles#2]
I'm having this problem with the chamber exteriors where if you place too many of them, the item count eventually gets too much for the chamber to be published. I was wondering if you could allow them to connect from corner to corner in order to kinda fill it that way rather than manually.

**Comment by MarcusKubis9** [comment]
I don't know why your asking this here.
